<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Subscription_subscribe</name>
   <tag></tag>
   <elementGuidId>5fb19c52-657f-4367-88db-0b1bd47a35d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subscribe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='subscribe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>15b5ed7b-65ea-42bf-a1b4-222adb7fa5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4ede84da-d828-4b83-99ac-4c4fd82c3f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subscribe</value>
      <webElementGuid>c6190baf-4326-41be-b64c-dfae9356e857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>b1f761f7-59b6-4909-8b38-b82a4efdd8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subscribe&quot;)</value>
      <webElementGuid>47f8bb1b-59df-4c88-9d39-bba5dff4db39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='subscribe']</value>
      <webElementGuid>86a55349-0ba3-4ba3-8c33-8cfc01610601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='footer']/div[2]/div/div/div[2]/div/form/button</value>
      <webElementGuid>45450290-5bba-41d9-a8df-4d908f52ba55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscription'])[1]/following::button[1]</value>
      <webElementGuid>4232585b-00dc-4451-826b-70291ca9402e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have been successfully subscribed!'])[1]/following::button[1]</value>
      <webElementGuid>5053f982-12b8-45d1-a3ae-c87a0553c2a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'subscribe', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>f91a269d-6d51-40a6-8343-f7bb9acec0e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>22e5ead8-6c68-4591-9b22-aa9b51409566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'subscribe']</value>
      <webElementGuid>aca9d3f8-9ade-4565-994f-98ca42894756</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
