<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Close</name>
   <tag></tag>
   <elementGuidId>adfec10c-76bd-43d8-94c9-0f2a8b4b590d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dismiss-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dismiss-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a8165880-c8cd-4ff5-9c59-7b6a2240b729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ns-wtnt9-e-16 button-common close-button</value>
      <webElementGuid>39814e90-b642-4262-925b-b33c768ea140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dismiss-button</value>
      <webElementGuid>649ad10d-327b-4bd6-9e31-dd719562f0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-ns-wtnt9-e</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>5db8ce34-efc6-4d27-a819-f327152454e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-overflow-forbidden</name>
      <type>Main</type>
      <value>xy</value>
      <webElementGuid>5c713925-ff43-4205-9dc1-e9b0e6c02dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close ad</value>
      <webElementGuid>377627ba-acbc-41b5-907d-773350037d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc37ff43-fac9-4b4a-ab69-d4f53b4f4777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dbddc0a2-1ba0-4d54-8fd6-d22e645e1e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>592561f1-fe22-436a-b5a2-1b712707069c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dismiss-button&quot;)</value>
      <webElementGuid>a196376d-be80-4bef-8486-875d4cb05621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Automation Exercise/iframe_Ad_ad_iframe</value>
      <webElementGuid>a333a73e-44ae-4cbf-88a8-41849c1ab931</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dismiss-button']</value>
      <webElementGuid>2ea10cff-5676-4969-aeda-381d73325ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='large-banner-eta-vanilla']/div/div[2]/div/div/div[3]</value>
      <webElementGuid>0eb00182-2fc6-4a7c-bc1a-987342f84f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='aot-technologies.com'])[1]/following::div[2]</value>
      <webElementGuid>e5aac142-7393-4820-b3da-16a2489d03f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Award-winning low code development by the fastestgrowing software company in BC, Canada.'])[1]/following::div[7]</value>
      <webElementGuid>18c145d2-c1cd-4f25-a8d6-516dab0c3cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/preceding::div[3]</value>
      <webElementGuid>659299b3-5a3b-4dc0-adc0-90ede33a6aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]</value>
      <webElementGuid>44d70ea6-e482-4037-8dc4-578220646dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dismiss-button' and (text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>20e5bfef-0b2a-471e-96cd-41041d763ac1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
