<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Subscription_fa fa-arrow-circle-o-right</name>
   <tag></tag>
   <elementGuidId>f2115d68-e641-4355-8f44-9742c7ca0d96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-arrow-circle-o-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='subscribe']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2134883e-8417-43fe-b55a-5748e7fadee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-arrow-circle-o-right</value>
      <webElementGuid>8cd666ca-cbaa-47e0-a732-aea7bb8d1368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subscribe&quot;)/i[@class=&quot;fa fa-arrow-circle-o-right&quot;]</value>
      <webElementGuid>d4fdb5ce-fa9d-4382-93a0-492d2030197f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='subscribe']/i</value>
      <webElementGuid>e6c1d342-ceb5-45f7-9c3b-28021a800942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>b68f27f9-b878-4062-a49b-e186d70d382d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
