<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Birth_newsletter</name>
   <tag></tag>
   <elementGuidId>7c7fd7da-31b2-4448-acbf-d5e8da36782e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#newsletter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='newsletter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ca6f051-8c17-4bf8-9570-cc5f8f08994d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>daff5a51-2ee3-44a1-b1aa-a49d77ff4b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>newsletter</value>
      <webElementGuid>2d2ba737-ad7a-4a97-8d1f-5a99a8e3f6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newsletter</value>
      <webElementGuid>66e8fa9c-2a44-4f60-8e7e-a67c1e56772e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b046f842-bd02-4b36-b718-5f00850ba478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newsletter&quot;)</value>
      <webElementGuid>6882c4e2-8e18-475e-8e4d-584f2a8fd7cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='newsletter']</value>
      <webElementGuid>9418ab6e-3a53-4178-ab79-0da68eeb8358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-newsletter']/span/input</value>
      <webElementGuid>689b0815-dbf7-43f7-8e2b-575e0162321d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/span/input</value>
      <webElementGuid>9a38b02b-fd3e-4109-9cc3-ab0370c66684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'newsletter' and @id = 'newsletter']</value>
      <webElementGuid>1295032e-32d2-4eeb-b597-f13736891971</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
