<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company_company</name>
   <tag></tag>
   <elementGuidId>19f54f54-ba05-4b12-ac93-461e086d0218</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#company</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='company']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b0e9ffe-88ae-47c1-8327-aba79eb27558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf32f22f-f96b-4985-85d1-5716d4aff239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>company</value>
      <webElementGuid>66585c43-a8c3-4b51-b2d2-9d65b347d6e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0f2a7237-8365-4dda-8721-eaecbe90b22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>company</value>
      <webElementGuid>d78beba6-cd9a-4639-9b7a-dfc50cefb4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company</value>
      <webElementGuid>099fe898-d624-43f6-8a97-3d6f1d0fa120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;company&quot;)</value>
      <webElementGuid>513214c0-8920-4eac-bbe6-2884da6ebe92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='company']</value>
      <webElementGuid>e0d84d7d-c8d1-4f7e-b972-b9f53a002bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='form']/div/div/div/div/form/p[3]/input</value>
      <webElementGuid>f3512add-2774-4977-8a1c-a7c113156b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/input</value>
      <webElementGuid>16a15a91-3c1a-418e-ac60-fe8a698623e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'company' and @name = 'company']</value>
      <webElementGuid>d32a010f-9f9f-4ad7-8caa-0bac7019e196</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
