<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_416-223-4452</name>
   <tag></tag>
   <elementGuidId>91092459-a8b7-429b-941e-d9d4198d7e39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.address_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='address_delivery']/li[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3b61356c-064d-4889-a1b1-5ca0feb2d0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>address_phone</value>
      <webElementGuid>c4c94c2a-d2de-44b0-8956-d95843a2fd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>416-223-4452</value>
      <webElementGuid>79fd2659-7598-4bc0-80c6-b6c98b518699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_delivery&quot;)/li[@class=&quot;address_phone&quot;]</value>
      <webElementGuid>22edc775-a279-4df2-9180-70b62c79abe9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='address_delivery']/li[8]</value>
      <webElementGuid>ea6d35be-9efa-4736-be8d-7e8f40ba20b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Canada'])[1]/following::li[1]</value>
      <webElementGuid>3c74ae8d-26d0-417f-aa02-fd3bdf5cc4d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your billing address'])[1]/preceding::li[1]</value>
      <webElementGuid>51f100ca-c67f-4f7d-a8b1-a96ef551ab41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mr. Billy Bob'])[2]/preceding::li[2]</value>
      <webElementGuid>9bc1728f-3ff4-4c9c-9658-9159c9a6cb68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='416-223-4452']/parent::*</value>
      <webElementGuid>c1a1a75c-accf-4da7-9aa1-e05b8f9b9327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul/li[8]</value>
      <webElementGuid>fd6117b3-ca23-4f0d-8171-c4c0431e486f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '416-223-4452' or . = '416-223-4452')]</value>
      <webElementGuid>781181dc-e6e1-4af8-9395-9d7add21ac2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
