<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_416-123-3321</name>
   <tag></tag>
   <elementGuidId>c5ce933c-b770-494a-ab96-c93de79fdca5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.address_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='address_delivery']/li[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>955ff4d1-e020-48a2-8a6e-eaef55225704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>address_phone</value>
      <webElementGuid>cc394009-d941-40fb-8e9c-82afe35367cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>416-123-3321</value>
      <webElementGuid>c625c5d2-2f02-4043-8e36-8aeaae816306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_delivery&quot;)/li[@class=&quot;address_phone&quot;]</value>
      <webElementGuid>3ff8694f-1cee-40fe-ba06-0a55c16648d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='address_delivery']/li[8]</value>
      <webElementGuid>0ecb967e-7c39-4c57-a91c-baf8c2118ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Canada'])[1]/following::li[1]</value>
      <webElementGuid>202eaad8-55c5-4e43-8b8f-60452ec6a016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your billing address'])[1]/preceding::li[1]</value>
      <webElementGuid>b18d8bbf-98af-4586-9785-b3c9a61ba59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mr. John Doe'])[2]/preceding::li[2]</value>
      <webElementGuid>f597174d-0c16-443a-bc06-ed00f6e86bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='416-123-3321']/parent::*</value>
      <webElementGuid>9689fa4f-b025-46ec-9218-f0cc6f1c603f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul/li[8]</value>
      <webElementGuid>54832292-6312-4a66-a3c7-393af2faf1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '416-123-3321' or . = '416-123-3321')]</value>
      <webElementGuid>9be0f2d3-01c8-4106-b8ba-e3721db8c94b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
