<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Canada</name>
   <tag></tag>
   <elementGuidId>3a24bbb0-3a15-4f2b-bae1-484c42bb6a85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.address_country_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='address_delivery']/li[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>46c69c5e-93b2-4ade-8069-2f795680b504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>address_country_name</value>
      <webElementGuid>d13eb496-5121-4536-8caf-bfc044f7b87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Canada</value>
      <webElementGuid>7e271aba-5a07-4953-bc63-686b08490ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address_delivery&quot;)/li[@class=&quot;address_country_name&quot;]</value>
      <webElementGuid>b284cf13-a71c-41cc-999c-ba05dc5f192e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='address_delivery']/li[7]</value>
      <webElementGuid>6b60c6d0-5e4a-46a0-8b01-d5894cbbdb6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RBC'])[1]/following::li[4]</value>
      <webElementGuid>1f1be4e3-a4d3-4dff-8597-3d62d7dfc766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your billing address'])[1]/preceding::li[2]</value>
      <webElementGuid>a4c788f7-2eac-43a7-99f6-6c34b3f8f204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mr. John Doe'])[2]/preceding::li[3]</value>
      <webElementGuid>c166e16a-c47c-4b6f-8166-8aeaa3b1f9ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Canada']/parent::*</value>
      <webElementGuid>a4082556-d4ff-4e4f-9dfe-b7e87aec21ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul/li[7]</value>
      <webElementGuid>19fb3802-570f-4ec0-ae27-b33dc26dda02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Canada' or . = 'Canada')]</value>
      <webElementGuid>6ae3051b-9ffc-43f9-8231-075d21b9ed9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
